/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtivacaoChipRouteImport } from './routes/ativacao-chip'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConexoesRouteImport } from './routes/conexoes'
import { Route as DisparosRouteImport } from './routes/disparos'
import { Route as FaturasRouteImport } from './routes/faturas'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PixRouteImport } from './routes/pix'
import { Route as QualidadeRouteImport } from './routes/qualidade'
import { Route as SafrasRouteImport } from './routes/safras'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as AtivacaoChipChatRouteImport } from './routes/ativacao-chip.chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivacaoChipRoute = AtivacaoChipRouteImport.update({
  id: '/ativacao-chip',
  path: '/ativacao-chip',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConexoesRoute = ConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DisparosRoute = DisparosRouteImport.update({
  id: '/disparos',
  path: '/disparos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturasRoute = FaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PixRoute = PixRouteImport.update({
  id: '/pix',
  path: '/pix',
  getParentRoute: () => rootRouteImport,
} as any)
const QualidadeRoute = QualidadeRouteImport.update({
  id: '/qualidade',
  path: '/qualidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SafrasRoute = SafrasRouteImport.update({
  id: '/safras',
  path: '/safras',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivacaoChipChatRoute = AtivacaoChipChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AtivacaoChipRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ativacao-chip': typeof AtivacaoChipRouteWithChildren
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRoute
  '/conexoes': typeof ConexoesRoute
  '/disparos': typeof DisparosRoute
  '/faturas': typeof FaturasRoute
  '/historico': typeof HistoricoRoute
  '/importar': typeof ImportarRoute
  '/perfil': typeof PerfilRoute
  '/pix': typeof PixRoute
  '/qualidade': typeof QualidadeRoute
  '/safras': typeof SafrasRoute
  '/supervisor': typeof SupervisorRoute
  '/tags': typeof TagsRoute
  '/ativacao-chip/chat': typeof AtivacaoChipChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ativacao-chip': typeof AtivacaoChipRouteWithChildren
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRoute
  '/conexoes': typeof ConexoesRoute
  '/disparos': typeof DisparosRoute
  '/faturas': typeof FaturasRoute
  '/historico': typeof HistoricoRoute
  '/importar': typeof ImportarRoute
  '/perfil': typeof PerfilRoute
  '/pix': typeof PixRoute
  '/qualidade': typeof QualidadeRoute
  '/safras': typeof SafrasRoute
  '/supervisor': typeof SupervisorRoute
  '/tags': typeof TagsRoute
  '/ativacao-chip/chat': typeof AtivacaoChipChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ativacao-chip': typeof AtivacaoChipRouteWithChildren
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRoute
  '/conexoes': typeof ConexoesRoute
  '/disparos': typeof DisparosRoute
  '/faturas': typeof FaturasRoute
  '/historico': typeof HistoricoRoute
  '/importar': typeof ImportarRoute
  '/perfil': typeof PerfilRoute
  '/pix': typeof PixRoute
  '/qualidade': typeof QualidadeRoute
  '/safras': typeof SafrasRoute
  '/supervisor': typeof SupervisorRoute
  '/tags': typeof TagsRoute
  '/ativacao-chip/chat': typeof AtivacaoChipChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ativacao-chip'
    | '/chat'
    | '/clientes'
    | '/conexoes'
    | '/disparos'
    | '/faturas'
    | '/historico'
    | '/importar'
    | '/perfil'
    | '/pix'
    | '/qualidade'
    | '/safras'
    | '/supervisor'
    | '/tags'
    | '/ativacao-chip/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ativacao-chip'
    | '/chat'
    | '/clientes'
    | '/conexoes'
    | '/disparos'
    | '/faturas'
    | '/historico'
    | '/importar'
    | '/perfil'
    | '/pix'
    | '/qualidade'
    | '/safras'
    | '/supervisor'
    | '/tags'
    | '/ativacao-chip/chat'
  id:
    | '__root__'
    | '/'
    | '/ativacao-chip'
    | '/chat'
    | '/clientes'
    | '/conexoes'
    | '/disparos'
    | '/faturas'
    | '/historico'
    | '/importar'
    | '/perfil'
    | '/pix'
    | '/qualidade'
    | '/safras'
    | '/supervisor'
    | '/tags'
    | '/ativacao-chip/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtivacaoChipRoute: typeof AtivacaoChipRouteWithChildren
  ChatRoute: typeof ChatRoute
  ClientesRoute: typeof ClientesRoute
  ConexoesRoute: typeof ConexoesRoute
  DisparosRoute: typeof DisparosRoute
  FaturasRoute: typeof FaturasRoute
  HistoricoRoute: typeof HistoricoRoute
  ImportarRoute: typeof ImportarRoute
  PerfilRoute: typeof PerfilRoute
  PixRoute: typeof PixRoute
  QualidadeRoute: typeof QualidadeRoute
  SafrasRoute: typeof SafrasRoute
  SupervisorRoute: typeof SupervisorRoute
  TagsRoute: typeof TagsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativacao-chip': {
      id: '/ativacao-chip'
      path: '/ativacao-chip'
      fullPath: '/ativacao-chip'
      preLoaderRoute: typeof AtivacaoChipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conexoes': {
      id: '/conexoes'
      path: '/conexoes'
      fullPath: '/conexoes'
      preLoaderRoute: typeof ConexoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disparos': {
      id: '/disparos'
      path: '/disparos'
      fullPath: '/disparos'
      preLoaderRoute: typeof DisparosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturas': {
      id: '/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof FaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pix': {
      id: '/pix'
      path: '/pix'
      fullPath: '/pix'
      preLoaderRoute: typeof PixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualidade': {
      id: '/qualidade'
      path: '/qualidade'
      fullPath: '/qualidade'
      preLoaderRoute: typeof QualidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safras': {
      id: '/safras'
      path: '/safras'
      fullPath: '/safras'
      preLoaderRoute: typeof SafrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativacao-chip/chat': {
      id: '/ativacao-chip/chat'
      path: '/chat'
      fullPath: '/ativacao-chip/chat'
      preLoaderRoute: typeof AtivacaoChipChatRouteImport
      parentRoute: typeof AtivacaoChipRoute
    }
  }
}

interface AtivacaoChipRouteChildren {
  AtivacaoChipChatRoute: typeof AtivacaoChipChatRoute
}

const AtivacaoChipRouteChildren: AtivacaoChipRouteChildren = {
  AtivacaoChipChatRoute: AtivacaoChipChatRoute,
}

const AtivacaoChipRouteWithChildren = AtivacaoChipRoute._addFileChildren(
  AtivacaoChipRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtivacaoChipRoute: AtivacaoChipRouteWithChildren,
  ChatRoute: ChatRoute,
  ClientesRoute: ClientesRoute,
  ConexoesRoute: ConexoesRoute,
  DisparosRoute: DisparosRoute,
  FaturasRoute: FaturasRoute,
  HistoricoRoute: HistoricoRoute,
  ImportarRoute: ImportarRoute,
  PerfilRoute: PerfilRoute,
  PixRoute: PixRoute,
  QualidadeRoute: QualidadeRoute,
  SafrasRoute: SafrasRoute,
  SupervisorRoute: SupervisorRoute,
  TagsRoute: TagsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
